"""Append out-of-sample prospective validation results to an eligible-player metrics CSV.

Win-percentage columns are proportions from 0 to 1. Point and game rates
use all complete observations in the chart, including tiebreak points and
games. Match rates exclude charts that do not end on a match-winning point.
"""

import pathlib
import sys
PRJ_DIR = pathlib.Path(__file__).parents[1]  # 2 levels up
sys.path.append(str(PRJ_DIR))

import argparse
import pandas as pd
from constants import GAME_STATES, MCP_DIR


DEFAULT_VALIDATION_START_DATE = pd.Timestamp("2025-05-25")
DEFAULT_VALIDATION_END_DATE   = pd.Timestamp("2026-05-24")

POINTS_FILE  = MCP_DIR / "charting-w-points-2020s.csv"
MATCHES_FILE = MCP_DIR / "charting-w-matches.csv"

SERVER_GAME_POINT_STATES   = {"40-0", "40-15", "40-30", "AD-40"}
RETURNER_GAME_POINT_STATES = {"0-40", "15-40", "30-40", "40-AD"}

COUNT_COLUMNS = [
    "validation_points",
    "validation_points_won",
    "validation_games",
    "validation_games_won",
    "validation_matches",
    "validation_matches_won" ]

# Convert a string "YYYY-MM-DD" to a pd.Timestamp representation
#
def parseDate(value: str) -> pd.Timestamp:
    try:
        date = pd.Timestamp(value)
    except (TypeError, ValueError) as ex:
        raise argparse.ArgumentTypeError(f"Invalid date {value!r}; use YYYY-MM-DD") from ex
    if pd.isna(date):
        raise argparse.ArgumentTypeError(f"Invalid date {value!r}; use YYYY-MM-DD")
    return date.normalize()


def parseArgs() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Calculate out-of-sample point-, game-, and match-win percentages for the eligible "
            "players in a metrics CSV, which has been generated by metrics-comparison.py "
            "(e.g., edge-dr-drplus-elo-wta-top100-20240525-20260524-min5-recent3.csv)"))
    parser.add_argument(
        "metrics_csv",
        type=pathlib.Path,
        help="Eligible-player CSV generated by metrics-comparison.py")
    parser.add_argument(
        "--validation-start",
        type=parseDate,
        default=DEFAULT_VALIDATION_START_DATE,
        help=(f"Validation start date, inclusive (default: {DEFAULT_VALIDATION_START_DATE:%Y-%m-%d})"))
    parser.add_argument(
        "--validation-end",
        type=parseDate,
        default=DEFAULT_VALIDATION_END_DATE,
        help=(f"Last validation date, inclusive (default: {DEFAULT_VALIDATION_END_DATE:%Y-%m-%d})"))
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        help=("Output CSV path. By default, a validation suffix is added to the input filename."))
    return parser.parse_args()


def validateColumns(
    df:              pd.DataFrame,
    requiredColumns: list[str],
    dataLabel:       str
) -> None:
    missingColumns = [ column for column in requiredColumns if column not in df.columns ]
    if missingColumns:
        raise ValueError(f"{dataLabel} is missing required columns: {missingColumns}")


def loadMetrics(metricsPath: pathlib.Path) -> pd.DataFrame:
    if not metricsPath.is_file():
        raise FileNotFoundError(f"Metrics CSV does not exist: {metricsPath}")

    metricsDf = pd.read_csv(metricsPath)
    validateColumns(metricsDf, ["player"], "Metrics CSV")

    metricsDf["player"] = metricsDf["player"].astype("string").str.strip()

    invalidPlayers = metricsDf["player"].isna() | metricsDf["player"].eq("")
    if invalidPlayers.any():
        raise ValueError("Metrics CSV contains a missing or blank player name")

    duplicatePlayers = metricsDf.loc[
        metricsDf["player"].duplicated(keep=False),
        "player",
    ].tolist()
    if duplicatePlayers:
        raise ValueError(
            f"Metrics CSV contains duplicate players: {duplicatePlayers}"
        )

    if metricsDf.empty:
        raise ValueError("Metrics CSV contains no eligible players")

    return metricsDf


def loadValidationData(
    eligiblePlayers: set[str],
    validationStartDate: pd.Timestamp,
    validationEndDate: pd.Timestamp,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    if validationStartDate > validationEndDate:
        raise ValueError(
            "Validation start date must not be after validation end date"
        )

    for inputPath in [POINTS_FILE, MATCHES_FILE]:
        if not inputPath.is_file():
            raise FileNotFoundError(f"MCP input file does not exist: {inputPath}")

    # Load the raw point file instead of MCPDataLoader.points. The loader
    # retains only standard-game score states and therefore omits most
    # tiebreak points, which must be included in prospective win rates.
    pointsDf = pd.read_csv(POINTS_FILE, dtype=str)
    matchesDf = pd.read_csv(MATCHES_FILE, dtype=str)

    validateColumns(
        pointsDf,
        [
            "match_id",
            "Pt",
            "Set1",
            "Set2",
            "Gm1",
            "Gm2",
            "Pts",
            "Gm#",
            "Svr",
            "PtWinner",
        ],
        "MCP point data",
    )
    validateColumns(
        matchesDf,
        ["match_id", "Player 1", "Player 2", "Date", "Best of"],
        "MCP match data",
    )

    loadedPointMatchIds = set(pointsDf["match_id"].dropna().unique())
    matchesDf = matchesDf.loc[
        matchesDf["match_id"].isin(loadedPointMatchIds)
    ].copy()

    if matchesDf["match_id"].duplicated().any():
        duplicateMatchIds = matchesDf.loc[
            matchesDf["match_id"].duplicated(keep=False),
            "match_id",
        ].tolist()
        raise ValueError(
            f"MCP match data contains duplicate match IDs: {duplicateMatchIds}"
        )

    matchesDf["match_date"] = pd.to_datetime(
        matchesDf["Date"],
        format="%Y%m%d",
        errors="raise",
    )
    matchesDf = matchesDf.loc[
        matchesDf["match_date"].between(
            validationStartDate,
            validationEndDate,
            inclusive="both",
        )
    ].copy()

    if matchesDf.empty:
        raise ValueError(
            "No charted MCP matches were found in the validation period"
        )

    matchesDf = matchesDf.loc[
        matchesDf["Player 1"].isin(eligiblePlayers)
        | matchesDf["Player 2"].isin(eligiblePlayers)
    ].copy()

    matchesDf["Best of"] = pd.to_numeric(
        matchesDf["Best of"],
        errors="coerce",
    ).astype("Int64")
    invalidBestOf = (
        matchesDf["Best of"].isna()
        | matchesDf["Best of"].le(0)
        | matchesDf["Best of"].mod(2).eq(0)
    )
    if invalidBestOf.any():
        invalidMatchIds = matchesDf.loc[
            invalidBestOf,
            "match_id",
        ].tolist()
        raise ValueError(
            f"Invalid match format for MCP matches: {invalidMatchIds}"
        )

    validationMatchIds = set(matchesDf["match_id"].dropna().unique())
    pointsDf = pointsDf.loc[
        pointsDf["match_id"].isin(validationMatchIds)
    ].copy()

    numericPointColumns = [
        "Pt",
        "Set1",
        "Set2",
        "Gm1",
        "Gm2",
        "Svr",
        "PtWinner",
    ]
    for column in numericPointColumns:
        pointsDf[column] = pd.to_numeric(
            pointsDf[column],
            errors="coerce",
        ).astype("Int64")

    invalidPointRows = (
        pointsDf[numericPointColumns].isna().any(axis=1)
        | pointsDf["Gm#"].isna()
        | pointsDf["Pts"].isna()
        | ~pointsDf["Svr"].isin([1, 2])
        | ~pointsDf["PtWinner"].isin([1, 2])
    )
    if invalidPointRows.any():
        invalidMatchIds = pointsDf.loc[
            invalidPointRows,
            "match_id",
        ].drop_duplicates().tolist()
        raise ValueError(
            "Validation point data contain invalid point number, game "
            f"number, or point winner for matches: {invalidMatchIds}"
        )

    pointsDf = pointsDf.sort_values(
        ["match_id", "Pt"]
    ).reset_index(drop=True)

    return pointsDf, matchesDf


def buildParticipantRows(
    matchesDf: pd.DataFrame,
    eligiblePlayers: set[str],
) -> pd.DataFrame:
    player1Df = matchesDf[
        ["match_id", "Player 1"]
    ].rename(columns={"Player 1": "player"})
    player1Df["player_number"] = 1

    player2Df = matchesDf[
        ["match_id", "Player 2"]
    ].rename(columns={"Player 2": "player"})
    player2Df["player_number"] = 2

    participantsDf = pd.concat(
        [player1Df, player2Df],
        ignore_index=True,
    )
    participantsDf = participantsDf.loc[
        participantsDf["player"].isin(eligiblePlayers)
    ].copy()
    participantsDf["player_number"] = participantsDf[
        "player_number"
    ].astype("Int64")

    if participantsDf.duplicated(["match_id", "player"]).any():
        raise ValueError(
            "An eligible player appears more than once in an MCP match"
        )

    return participantsDf


def pointEndsGame(pointRow: pd.Series) -> bool:
    score = str(pointRow["Pts"]).strip()
    server = int(pointRow["Svr"])
    pointWinner = int(pointRow["PtWinner"])

    if pointWinner == server and score in SERVER_GAME_POINT_STATES:
        return True
    if pointWinner != server and score in RETURNER_GAME_POINT_STATES:
        return True
    if score in GAME_STATES:
        return False

    # Tiebreak scores are numeric and written from the server's
    # perspective, like the standard point score.
    try:
        serverPoints, returnerPoints = [
            int(value) for value in score.split("-", maxsplit=1)
        ]
    except (TypeError, ValueError):
        return False

    if pointWinner == server:
        serverPoints += 1
        winnerPoints = serverPoints
        loserPoints = returnerPoints
    else:
        returnerPoints += 1
        winnerPoints = returnerPoints
        loserPoints = serverPoints

    return winnerPoints >= 7 and winnerPoints - loserPoints >= 2


def pointEndsMatch(pointRow: pd.Series) -> bool:
    if not pointEndsGame(pointRow):
        return False

    pointWinner = int(pointRow["PtWinner"])
    player1Games = int(pointRow["Gm1"])
    player2Games = int(pointRow["Gm2"])

    if pointWinner == 1:
        player1Games += 1
        winnerGames = player1Games
        loserGames = player2Games
        setsWonBeforePoint = int(pointRow["Set1"])
    else:
        player2Games += 1
        winnerGames = player2Games
        loserGames = player1Games
        setsWonBeforePoint = int(pointRow["Set2"])

    wonSet = (
        (winnerGames >= 6 and winnerGames - loserGames >= 2)
        or (winnerGames == 7 and loserGames == 6)
    )
    if not wonSet:
        return False

    setsNeeded = int(pointRow["Best of"]) // 2 + 1
    return setsWonBeforePoint + 1 >= setsNeeded


def summarizeOutcomes(
    outcomeRowsDf: pd.DataFrame,
    participantsDf: pd.DataFrame,
    unitName: str,
) -> pd.DataFrame:
    playerOutcomesDf = outcomeRowsDf[
        ["match_id", "PtWinner"]
    ].merge(
        participantsDf,
        on="match_id",
        how="inner",
        validate="many_to_many",
    )
    playerOutcomesDf["won"] = (
        playerOutcomesDf["PtWinner"]
        == playerOutcomesDf["player_number"]
    )

    return (
        playerOutcomesDf
        .groupby("player", as_index=False)
        .agg(
            **{
                f"validation_{unitName}": ("won", "size"),
                f"validation_{unitName}_won": ("won", "sum"),
            }
        )
    )


def calculateProspectiveStats(
    metricsDf: pd.DataFrame,
    pointsDf: pd.DataFrame,
    matchesDf: pd.DataFrame,
) -> pd.DataFrame:
    eligiblePlayers = set(metricsDf["player"])
    participantsDf = buildParticipantRows(matchesDf, eligiblePlayers)

    pointStatsDf = summarizeOutcomes(
        pointsDf,
        participantsDf,
        "points",
    )

    gameLastPointRowsDf = (
        pointsDf
        .groupby(["match_id", "Gm#"], sort=False)
        .tail(1)
    )
    if gameLastPointRowsDf.empty:
        completedGameMask = pd.Series(
            index=gameLastPointRowsDf.index,
            dtype=bool,
        )
    else:
        completedGameMask = gameLastPointRowsDf.apply(
            pointEndsGame,
            axis=1,
        ).astype(bool)
    gameResultRowsDf = gameLastPointRowsDf.loc[
        completedGameMask
    ].copy()
    gameStatsDf = summarizeOutcomes(
        gameResultRowsDf,
        participantsDf,
        "games",
    )

    matchLastPointRowsDf = (
        pointsDf
        .groupby("match_id", sort=False)
        .tail(1)
        .merge(
            matchesDf[["match_id", "Best of"]],
            on="match_id",
            how="left",
            validate="one_to_one",
        )
    )
    if matchLastPointRowsDf.empty:
        completedMatchMask = pd.Series(
            index=matchLastPointRowsDf.index,
            dtype=bool,
        )
    else:
        completedMatchMask = matchLastPointRowsDf.apply(
            pointEndsMatch,
            axis=1,
        ).astype(bool)
    matchResultRowsDf = matchLastPointRowsDf.loc[
        completedMatchMask
    ].copy()

    incompleteGameCount = int((~completedGameMask).sum())
    incompleteMatchCount = int((~completedMatchMask).sum())
    if incompleteGameCount:
        print(
            "Excluded incomplete games from game-win percentage: "
            f"{incompleteGameCount}"
        )
    if incompleteMatchCount:
        print(
            "Excluded incomplete matches from match-win percentage: "
            f"{incompleteMatchCount}"
        )

    matchStatsDf = summarizeOutcomes(
        matchResultRowsDf,
        participantsDf,
        "matches",
    )

    validationDf = metricsDf[["player"]].copy()
    validationDf = (
        validationDf
        .merge(pointStatsDf, on="player", how="left", validate="one_to_one")
        .merge(gameStatsDf, on="player", how="left", validate="one_to_one")
        .merge(matchStatsDf, on="player", how="left", validate="one_to_one")
    )

    validationDf[COUNT_COLUMNS] = (
        validationDf[COUNT_COLUMNS]
        .fillna(0)
        .astype("Int64")
    )

    for unitName, singularUnitName in [
        ("points", "point"),
        ("games", "game"),
        ("matches", "match"),
    ]:
        totalColumn = f"validation_{unitName}"
        wonColumn = f"validation_{unitName}_won"
        percentageColumn = f"validation_{singularUnitName}_win_pct"

        validationDf[percentageColumn] = (
            validationDf[wonColumn]
            / validationDf[totalColumn].replace(0, pd.NA)
        ).astype("Float64")

    validationColumnOrder = [
        "validation_points",
        "validation_points_won",
        "validation_point_win_pct",
        "validation_games",
        "validation_games_won",
        "validation_game_win_pct",
        "validation_matches",
        "validation_matches_won",
        "validation_match_win_pct",
    ]

    resultDf = metricsDf.merge(
        validationDf[["player", *validationColumnOrder]],
        on="player",
        how="left",
        validate="one_to_one",
        sort=False,
    )

    if resultDf["player"].tolist() != metricsDf["player"].tolist():
        raise ValueError("Eligible-player order changed during validation merge")

    return resultDf


def defaultOutputPath(
    metricsPath:         pathlib.Path,
    validationStartDate: pd.Timestamp,
    validationEndDate:   pd.Timestamp,
) -> pathlib.Path:
    outputName = (
        f"{metricsPath.stem}-prospective-"
        f"{validationStartDate:%Y%m%d}-{validationEndDate:%Y%m%d}.csv")
    return metricsPath.with_name(outputName)


def main() -> None:
    args = parseArgs()
    metricsPath = args.metrics_csv.resolve()
    outputPath = (
        args.output.resolve()
        if args.output is not None
        else defaultOutputPath(
            metricsPath,
            args.validation_start,
            args.validation_end) )

    if outputPath == metricsPath:
        raise ValueError("Output CSV must not overwrite the metrics input CSV")

    metricsDf           = loadMetrics(metricsPath)
    eligiblePlayers     = set(metricsDf["player"])
    pointsDf, matchesDf = loadValidationData(
        eligiblePlayers, args.validation_start, args.validation_end)
    
    resultDf = calculateProspectiveStats( metricsDf, pointsDf, matchesDf )

    outputPath.parent.mkdir(parents=True, exist_ok=True)
    resultDf.to_csv(outputPath, index=False)

    playersWithMatches = int(
        resultDf["validation_matches"].gt(0).sum()
    )
    print(
        "Validation period: "
        f"{args.validation_start:%Y-%m-%d} through "
        f"{args.validation_end:%Y-%m-%d}"
    )
    print(f"Eligible players: {len(resultDf)}")
    print(
        "Players with completed charted validation matches: "
        f"{playersWithMatches}"
    )
    print(f"Saved to: {outputPath}")


if __name__ == "__main__":
    main()
